export const GET_INVOICES_ITEMS_REQUEST = 'GET_INVOICES_ITEMS_REQUEST';
export const GET_INVOICES_ITEMS_SUCCESS = 'GET_INVOICES_ITEMS_SUCCESS';
export const GET_INVOICES_ITEMS_FAIL = 'GET_INVOICES_ITEMS_FAIL';

export const POST_INVOICES_ITEMS_REQUEST = 'POST_INVOICES_ITEMS_REQUEST';
export const POST_INVOICES_ITEMS_SUCCESS = 'POST_INVOICES_ITEMS_SUCCESS';
export const POST_INVOICES_ITEMS_FAIL = 'POST_INVOICES_ITEMS_FAIL';

export const ADD_QUEUE_DELETE = 'ADD_QUEUE_DELETE';
export const CLEAR_QUEUE_DELETE = 'CLEAR_QUEUE_DELETE';

export const ADD_QUEUE_EDIT = 'ADD_QUEUE_EDIT';
export const CLEAR_QUEUE_EDIT = 'CLEAR_QUEUE_EDIT';

export const DELETE_INVOICES_ITEMS_REQUEST = 'DELETE_INVOICES_ITEMS_REQUEST';
export const DELETE_INVOICES_ITEMS_SUCCESS = 'DELETE_INVOICES_ITEMS_SUCCESS';
export const DELETE_INVOICES_ITEMS_FAIL = 'DELETE_INVOICES_ITEMS_FAIL';

export const EDIT_INVOICES_ITEMS_REQUEST = 'EDIT_INVOICES_ITEMS_REQUEST';
export const EDIT_INVOICES_ITEMS_SUCCESS = 'EDIT_INVOICES_ITEMS_SUCCESS';
export const EDIT_INVOICES_ITEMS_FAIL = 'EDIT_INVOICES_ITEMS_FAIL';