export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';

export const POST_PRODUCTS_REQUEST = 'POST_PRODUCTS_REQUEST';
export const POST_PRODUCTS_SUCCESS = 'POST_PRODUCTS_SUCCESS';
export const POST_PRODUCTS_FAIL = 'POST_PRODUCTS_FAIL';

export const ADD_QUEUE_DELETE = 'ADD_QUEUE_DELETE';
export const CLEAR_QUEUE_DELETE = 'CLEAR_QUEUE_DELETE';

export const ADD_QUEUE_EDIT = 'ADD_QUEUE_EDIT';
export const CLEAR_QUEUE_EDIT = 'CLEAR_QUEUE_EDIT';

export const DELETE_PRODUCTS_REQUEST = 'DELETE_PRODUCTS_REQUEST';
export const DELETE_PRODUCTS_SUCCESS = 'DELETE_PRODUCTS_SUCCESS';
export const DELETE_PRODUCTS_FAIL = 'DELETE_PRODUCTS_FAIL';

export const EDIT_PRODUCTS_REQUEST = 'EDIT_PRODUCTS_REQUEST';
export const EDIT_PRODUCTS_SUCCESS = 'EDIT_PRODUCTS_SUCCESS';
export const EDIT_PRODUCTS_FAIL = 'EDIT_PRODUCTS_FAIL';